import Link from 'next/link';

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white/80 font-sans selection:bg-[#cfa670]/30 overflow-y-auto">
      <div className="max-w-3xl mx-auto px-6 py-20 md:py-32">
        <Link href="/" className="inline-block mb-12 text-[#cfa670] hover:text-[#e5c597] transition-colors font-serif tracking-widest text-sm uppercase">
          &larr; Return to Temple
        </Link>

        <h1 className="text-4xl md:text-5xl font-serif text-[#cfa670] mb-8 leading-tight">Terms of Service</h1>
        
        <div className="prose prose-invert prose-lg max-w-none prose-p:leading-relaxed prose-headings:font-serif prose-headings:text-[#cfa670]">
          <p className="text-sm text-white/50 mb-8">Last Updated: June 2026</p>

          <p>
            Welcome to BuddhaLove. By accessing or using our website, you agree to be bound by these Terms of Service. 
            If you do not agree with any part of these terms, you may not access the Service.
          </p>

          <h2>1. Use of the Service</h2>
          <p>
            BuddhaLove provides a digital sanctuary featuring an interactive AI-driven conversational interface and visual meditation tools. 
            You agree to use the Service only for lawful purposes and in a manner that does not infringe the rights of, 
            restrict, or inhibit anyone else's use and enjoyment of the Service.
          </p>

          <h2>2. AI Interactions and Disclaimer</h2>
          <p>
            The responses provided by the "digital Buddha" are generated by artificial intelligence (AI). They are for 
            entertainment, reflection, and philosophical contemplation only. We do not guarantee the accuracy, completeness, 
            or appropriateness of any AI-generated content.
          </p>
          <p>
            <strong>Medical/Psychological Disclaimer:</strong> The Service is not a substitute for professional mental health care, 
            therapy, or medical advice. If you are experiencing psychological distress, please contact a qualified healthcare provider 
            or emergency services in your region immediately.
          </p>

          <h2>3. Donations (Offerings)</h2>
          <p>
            Through our Service, you may choose to make voluntary donations ("Offerings") via third-party payment processors 
            (such as Ko-fi or PayPal). These offerings are strictly voluntary. We do not store your payment information on our servers. 
            All transactions are subject to the terms and conditions of the respective third-party payment providers.
          </p>

          <h2>4. Intellectual Property</h2>
          <p>
            The Service and its original content, features, and functionality are and will remain the exclusive property of 
            BuddhaLove and its licensors. You may not reproduce, distribute, or create derivative works from this content 
            without explicit permission, except for standard social media sharing features provided within the app.
          </p>

          <h2>5. Limitation of Liability</h2>
          <p>
            In no event shall BuddhaLove, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable 
            for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, 
            data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
          </p>

          <h2>6. Changes to Terms</h2>
          <p>
            We reserve the right, at our sole discretion, to modify or replace these Terms at any time. By continuing to access 
            or use our Service after those revisions become effective, you agree to be bound by the revised terms.
          </p>

          <h2>7. Contact Us</h2>
          <p>
            If you have any questions about these Terms, please contact us at: <br/>
            <a href="mailto:hello@validschwenk.com" className="text-[#cfa670] hover:underline">hello@validschwenk.com</a>
          </p>
        </div>
      </div>
    </div>
  );
}
